In [22]:
# M. Yusril Nugraha P (17523117)
# Zikri Dwi Andika (17523226)

In [21]:
# exercise
# 1. Use power method to approximate a dominant eigenvalue and the corresponding eigenvector.
# 2. Using Power Method, find the dominant eigenvalue and the corresponding eigenvector.

In [166]:
# Answer 
# matrix <=> A <- matrix(c(4, -5, 2, 3), 2, 2, TRUE)
# no 1.
A <- matrix(c(4, -5, 2, -3), 2, 2, TRUE)
A

# dengan 5x iterasi, dan X0 <- matrix(c(1, 0), 1, 1, TRUE)
X0 <- matrix(c(1, 0), 2, 1, TRUE)
X0

[,1] [,2]
[1,] 4    -5  
[2,] 2    -3

[,1]
[1,] 1   
[2,] 0

In [59]:
# X1 <- iterasi 1
X1 <- A %*% X0
X1
eigen <- X1/4
eigen

[,1]
[1,] 4   
[2,] 2

[,1]
[1,] 1.0 
[2,] 0.5

In [61]:
# X2 <- iterasi 2
X2 <- A %*% X1
X2
eigen <- X2/6
eigen

[,1]
[1,] 6   
[2,] 2

[,1]     
[1,] 1.0000000
[2,] 0.3333333

In [63]:
# X3 <- iterasi 3
X3 <- A %*% X2
X3
eigen <- X3/14
eigen

[,1]
[1,] 14  
[2,]  6

[,1]     
[1,] 1.0000000
[2,] 0.4285714

In [66]:
# X4 <- iterasi 4
X4 <- A %*% X3
X4
eigen <- X4/26
eigen

[,1]
[1,] 26  
[2,] 10

[,1]     
[1,] 1.0000000
[2,] 0.3846154

In [68]:
# X5 <- iterasi 5
X5 <- A %*% X4
X5
eigen <- X5/54
eigen

[,1]
[1,] 54  
[2,] 22

[,1]     
[1,] 1.0000000
[2,] 0.4074074

In [30]:
# matrix <=> B <- matrix(c(0, 11, -5, 
#                         -2, 17, -7
#                         -4, 26, -10), 3, 3, TRUE)
B <- matrix(c(0, 11, -5, 
             -2, 17, -7,
             -4, 26, -10), 3, 3, TRUE)
B

# dengan 10x iterasi, dan X0 <- matrix(c(1, 1, 1), 3, 1, TRUE)
X0 <- matrix(c(1, 1, 1), 3, 1, TRUE)
X0

[,1] [,2] [,3]
[1,]  0   11    -5 
[2,] -2   17    -7 
[3,] -4   26   -10

[,1]
[1,] 1   
[2,] 1   
[3,] 1

In [35]:
# X1 <- iterasi 1

X1 <- B %*% X0
X1
eigen <- X1/12
eigen

[,1]
[1,]  6  
[2,]  8  
[3,] 12

[,1]     
[1,] 0.5000000
[2,] 0.6666667
[3,] 1.0000000

In [38]:
# X2 <- iterasi 2
X2 <- B %*% X1
X2
eigen <- X2/64
eigen

[,1]
[1,] 28  
[2,] 40  
[3,] 64

[,1]  
[1,] 0.4375
[2,] 0.6250
[3,] 1.0000

In [40]:
# X3 <- iterasi 3
X3 <- B %*% X2
X3
eigen <- X3/288
eigen

[,1]
[1,] 120 
[2,] 176 
[3,] 288

[,1]     
[1,] 0.4166667
[2,] 0.6111111
[3,] 1.0000000

In [42]:
# X4 <- iterasi 4
X4 <- B %*% X3
X4
eigen <- X4/1216
eigen

[,1]
[1,]  496
[2,]  736
[3,] 1216

[,1]     
[1,] 0.4078947
[2,] 0.6052632
[3,] 1.0000000

In [44]:
# X5 <- iterasi 5
X5 <- B %*% X4
X5
eigen <- X5/4992
eigen

[,1]
[1,] 2016
[2,] 3008
[3,] 4992

[,1]     
[1,] 0.4038462
[2,] 0.6025641
[3,] 1.0000000

In [46]:
# X6 <- iterasi 6
X6 <- B %*% X5
X6
eigen <- X6/20224
eigen

[,1] 
[1,]  8128
[2,] 12160
[3,] 20224

[,1]     
[1,] 0.4018987
[2,] 0.6012658
[3,] 1.0000000

In [48]:
# X7 <- iterasi 7
X7 <- B %*% X6
X7
eigen <- X7/81408
eigen

[,1] 
[1,] 32640
[2,] 48896
[3,] 81408

[,1]     
[1,] 0.4009434
[2,] 0.6006289
[3,] 1.0000000

In [50]:
# X8 <- iterasi 8
X8 <- B %*% X7
X8
eigen <- X8/326656
eigen

[,1]  
[1,] 130816
[2,] 196096
[3,] 326656

[,1]     
[1,] 0.4004702
[2,] 0.6003135
[3,] 1.0000000

In [52]:
# X9 <- iterasi 9
X9 <- B %*% X8
X9
eigen <- X9/1308672
eigen

[,1]   
[1,]  523776
[2,]  785408
[3,] 1308672

[,1]     
[1,] 0.4002347
[2,] 0.6001565
[3,] 1.0000000

In [54]:
# X10 <- iterasi 10
X10 <- B %*% X9
X10
eigen <- X10/5238784
eigen

[,1]   
[1,] 2096128
[2,] 3143680
[3,] 5238784

[,1]     
[1,] 0.4001173
[2,] 0.6000782
[3,] 1.0000000

In [120]:
# matrix <=> A <- matrix(c(4, -5, 2, 3), 2, 2, TRUE)
# eigen = X <- matrix(c(1.0000000, 0.4074074), 2, 1, TRUE)
# no 2.

A <- matrix(c(4, -5, 2, 3), 2, 2, TRUE)
A
X <- matrix(c(1.0000, 0.4074), 2, 1, TRUE)
X

[,1] [,2]
[1,] 4    -5  
[2,] 2     3

[,1]  
[1,] 1.0000
[2,] 0.4074

In [138]:
AX <- A %*% X
AX

[,1]  
[1,] 1.9630
[2,] 0.7778

In [195]:
AXX <- AX * X
AXX
AXX <- 1.963000 + 0.3168757
AXX

[,1]     
[1,] 1.9630000
[2,] 0.3168757

[1] 2.279876

In [198]:
XX <- X * X
XX
XX <- 1.0000000 + 0.1659748
XX

[,1]     
[1,] 1.0000000
[2,] 0.1659748

[1] 1.165975

In [206]:
eigenvalue_dominan <- AXX/XX
eigenvalue_dominan

[1] 1.955339

In [207]:
powerMethod(A)

$vector_iterations
     v1         v2
[1,]  1 -0.7071068
[2,]  1 -0.7071068

$iter
[1] 2

$vector
          [,1]
[1,] 0.7071068
[2,] 0.7071068

$value
[1] -1

In [200]:
# matrix <=> B <- matrix(c(0, 11, -5, 
#                         -2, 17, -7
#                         -4, 26, -10), 3, 3, TRUE)
# eigen = X <- matrix(c(0.4001173, 0.6000782, 1.0000000), 3, 1, TRUE)
# no 2.
B <- matrix(c(0, 11, -5, 
             -2, 17, -7,
             -4, 26, -10), 3, 3, TRUE)
B
X <- matrix(c(0.4001173, 0.6000782, 1.0000000), 3, 1, TRUE)
X


[,1] [,2] [,3]
[1,]  0   11    -5 
[2,] -2   17    -7 
[3,] -4   26   -10

[,1]     
[1,] 0.4001173
[2,] 0.6000782
[3,] 1.0000000

In [201]:
BX <- B %*% X
BX

[,1]    
[1,] 1.600860
[2,] 2.401095
[3,] 4.001564

In [203]:
BXX <- BX * X
BXX
BXX <- 1.600860 + 2.401095 + 4.001564
BXX

[,1]     
[1,] 0.6405319
[2,] 1.4408446
[3,] 4.0015640

[1] 8.003519

In [204]:
eigenvalue_dominan <- BXX/XX
eigenvalue_dominan

[1] 6.86423

In [205]:
powerMethod(B)

$vector_iterations
     v1        v2        v3        v4        v5        v6        v7        v8
[1,]  1 0.3841106 0.3478328 0.3349917 0.3294704 0.3268991 0.3256571 0.3250465
[2,]  1 0.5121475 0.4969040 0.4913212 0.4888916 0.4877542 0.4872035 0.4869325
[3,]  1 0.7682213 0.7950464 0.8039801 0.8077340 0.8094645 0.8102964 0.8107043
            v9       v10       v11       v12       v13       v14       v15
[1,] 0.3247438 0.3245931 0.3245179 0.3244804 0.3244616 0.3244522 0.3244475
[2,] 0.4867980 0.4867311 0.4866976 0.4866809 0.4866726 0.4866684 0.4866663
[3,] 0.8109064 0.8110069 0.8110570 0.8110821 0.8110946 0.8111009 0.8111040
           v16       v17
[1,] 0.3244452 0.3244440
[2,] 0.4866653 0.4866648
[3,] 0.8111055 0.8111063

$iter
[1] 17

$vector
          [,1]
[1,] 0.3244434
[2,] 0.4866645
[3,] 0.8111067

$value
[1] 4.000011